language: php

php:
  - '7.0'

addons:
  ssh_known_hosts: $DEPLOY_SERVER

before_install:
  - nvm install 4
  - nvm use 4

install:
  - git --version
  - php -v
  - composer --version
  - node -v

  - composer install
  - npm install

script:
  - ./node_modules/.bin/gulp build
  - phpunit --coverage-text

before_deploy:
  - tar czf ./calendar-$TRAVIS_BUILD_NUMBER.tar.gz -C ./ ./app ./bin ./src ./vendor ./web ./var
  - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: bin/deploy ./calendar-$TRAVIS_BUILD_NUMBER.tar.gz $DEPLOY_USER $DEPLOY_SERVER $DEPLOY_PATH $TRAVIS_BUILD_NUMBER
  on:
    branch: development


