sudo: required

services:
  - docker

language: go

go:
  - 1.7

addons:
  ssh_known_hosts: $DEPLOY_SERVER

before_install:
  - make clean
  - nvm install 4
  - nvm use 4

install:
  - git --version
  - go version
  - node -v


script:
  - make all
  - make cross
