language: php

php:
  - '7.0'

services:
  - mysql

addons:
  ssh_known_hosts: $DEPLOY_SERVER

before_install:
  - nvm install 4
  - nvm use 4
  - npm install -g yarn

  - cp api/app/config/parameters.yml.travis api/app/config/parameters.yml.dist
  - cp frontend/src/js/config.dist.json frontend/src/js/config.json

install:
  - git --version
  - php -v
  - composer --version
  - node -v

  - pushd api
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console calendar:import ical-tcl ./data/simple-calendar
  - popd

  - pushd frontend
  - yarn install
  - popd

script:
  - pushd frontend
  - ./node_modules/.bin/gulp build
  - popd

  - phpunit --coverage-text -c ./api

before_deploy:
  - tar czf ./calendar-$TRAVIS_BUILD_NUMBER.tar.gz -C ./ ./api/app ./api/bin ./api/src ./api/vendor ./api/web ./api/var ./frontend/index.html ./frontend/assets
  - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy ./calendar-$TRAVIS_BUILD_NUMBER.tar.gz $DEPLOY_USER $DEPLOY_SERVER $DEPLOY_PATH $TRAVIS_BUILD_NUMBER
  on:
    branch: development


