language: php

php:
  - '7.0'

addons:
  ssh_known_hosts: $DEPLOY_SERVER

before_install:
  - nvm install 4
  - nvm use 4
  - npm install -g yarn

install:
  - git --version
  - php -v
  - composer --version
  - node -v

  - pushd api
  - composer install
  - popd

  - pushd frontend
  - yarn install
  - popd

script:
  - pushd frontend
  - ./node_modules/.bin/gulp build
  - popd

  - phpunit --coverage-text -c ./api

before_deploy:
  - tar czf ./calendar-$TRAVIS_BUILD_NUMBER.tar.gz -C ./ ./api/app ./api/bin ./api/src ./api/vendor ./api/web ./api/var ./frontend/index.html ./frontend/assets
  - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy ./calendar-$TRAVIS_BUILD_NUMBER.tar.gz $DEPLOY_USER $DEPLOY_SERVER $DEPLOY_PATH $TRAVIS_BUILD_NUMBER
  on:
    branch: development


