language: php

php:
  - '7.0'
  - 'nightly'

before_install:
  - nvm install 4.5
  - nvm use 4.5

install:
  - git --version
  - php -v
  - composer --version
  - node -v

  - composer install
  - npm install

script:
  - ./node_modules/.bin/gulp build
  - phpunit


