# where to output logs to.
# if not set, logs to /dev/null, "stdout" will log to stdout. anything else logs to the given file location
log_output: stdout

database:
  # dialect can either be "sqlite3" or "mysql"
  dialect: sqlite3

  # where to store the calendar database.
  location: ~/.myCal.db

  # mysql extra config opts
  # hostname: localhost
  # port: 3306
  # username: root
  # password: abcd1234
  # database: calendar

web:
  address: 0.0.0.0
  port: 8000

  # location of frontend code. to use inbuilt files (production)
  # comment this line out.
  # static_files: frontend/
