database:
  # dialect can either be "sqlite3" or "mysql"
  # mysql has more parameters, see config/parse.go for details.
  dialect: mysql
  hostname: localhost
  port: 3306
  username: root
  password: abcd1234
  database: calendar

  # where to store the calendar database.
  location: ./cal-db.db

web:
  address: 0.0.0.0
  port: 8000

  # location of frontend code. to use inbuilt files (production)
  # comment this line out.
  static_files: frontend/
