version: "2"

services:
  web:
    image: seeruk/docker-nginx:latest
    environment:
      NGINX_TEMPLATE: default-php-symfony2
      PHP_INDEX: app_dev.php
    ports:
    - 80:8080
    - 443:4430
    volumes:
    - .:/opt/www
    links:
    - php:php.docker

  php:
    image: seeruk/php-fpm:7.0-dev
    environment:
      PHP_UID: 501
      PHP_GID: 20
    volumes:
    - .:/opt/www
    links:
    - db:db.docker

  db:
    image: mysql:latest
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=calendar

  node:
    image: node:4.5
    volumes:
    - .:/app
    # keep these off the machine, eases permissions.
    - /app/.npm
    - /app/node_modules
    working_dir: /app
    command: bash -c "npm install && node_modules/.bin/gulp watch"

volumes:
  dbdata:
    driver: local
