version: "2"

services:
  web:
    image: seeruk/docker-nginx:latest
    environment:
      NGINX_TEMPLATE: default-php-symfony2
      PHP_INDEX: app_dev.php
    ports:
    - 443:4430
    volumes:
    - ./api:/opt/www
    links:
    - php:php.docker

  php:
    image: seeruk/php-fpm:7.0-dev
    environment:
      PHP_UID: 501
      PHP_GID: 20
    volumes:
    - ./api:/opt/www
    links:
    - db:db.docker

  db:
    image: mysql:latest
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=calendar
    ports:
    - 3306:3306

  frontend:
    image: nginx:latest
    volumes:
    - ./frontend:/usr/share/nginx/html
    ports:
    - 80:80

volumes:
  dbdata:
    driver: local
