calendar_appointments:
    path:     /calendar/appointments
    defaults: { _controller: calendar.controller.calendar:appointmentsAction }

calendar_notes:
    path:     /calendar/notes
    defaults: { _controller: calendar.controller.calendar:notesAction }

calendar_options:
    path:     /calendar/options
    defaults: { _controller: calendar.controller.calendar:optionsAction }

calendar_import:
    path:     /calendar/import
    defaults: { _controller: calendar.controller.calendar:importAction }
