services:
    calendar.command.import:
        class: CalendarBundle\Command\ImportCalendarCommand
        tags:
            - { name: console.command }
        arguments: [ null, "@doctrine.orm.entity_manager", "@logger" ]

    calendar.repository.appointment:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:
            - CalendarBundle\Entity\Appointment

    calendar.repository.note:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments:
            - CalendarBundle\Entity\Note

    calendar.defaults.option_map:
        class: CalendarBundle\Defaults\OptionMap

    calendar.controller.calendar:
        class: CalendarBundle\Controller\CalendarController
        arguments: [ "@logger", "@jms_serializer", "@doctrine.orm.entity_manager", "@calendar.repository.appointment", "@calendar.repository.note", "@calendar.defaults.option_map" ]
