services:
    calendar.command.import:
        class: CalendarBundle\Command\ImportCalendarCommand
        tags:
            - { name: console.command }
        arguments: [ null, "@doctrine.orm.entity_manager", "@logger" ]
