database:
  dialect: mysql
  location: /tmp/cal-db1.db
  username: root
  password: abcd1234
  hostname: localhost
  database: calendar
  port: 3306

web:
  address: 0.0.0.0
  port: 8000
  static_files: ../../frontend
