<?php

namespace CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarOptionRepository extends EntityRepository
{
}
