<?php

namespace CalendarBundle\Repository;

/**
 * CalendarOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
